### ISSUE TITLE
Error with opengl 3.3 driver

### ISSUE THREAD

**Issue by jice-nospam** [edwin0cheng/unigame#11]
```
> cargo run --release
opengl 3.3 (Core profile) Mesa 17.2.8
shading language 3.30
vendor VMWare, Inc.
[...]
thread 'main' panicked at 'GLError : vertex attrib pointer 1282 (invalid operation)', webgl/src/webgl_native.rs:17:13
[...]
6: webgl::webgl::<impl webgl::common::GLContext>::vertex_attrib_pointer
```

So it appears certain versions of opengl require a vertex array object to be able to call vertex_attrib_pointer. This seems to depends whether you're using compatibility (works without VAO) or core profile (requires VAO).

Adding a vao fixes the native version, but breaks the web version as VAO is only supported in webgl 2.0 :
https://developer.mozilla.org/en-US/docs/Web/API/WebGLVertexArrayObject

I don't know if there's a common way to make it work for every version or if we need to branch code depending on the driver version.

I managed to make it work for both native and web version, but this relies on parsing the GetString(gl::VERSION) string, which is crappy...

**Comment by edwin0cheng** [comment]
How can i reproduce this bug in my machine? How can i setup the VM you use?

**Comment by jice-nospam** [comment]
I'm using Virtual Box with a ubuntu 17.10 image. It might also depend on my laptop opengl drivers. I've got a HP EliteBook 840 with an Intel HD 5500 graphics card. it will probably be a pain to reproduce...

**Comment by jice-nospam** [comment]
One way might be to enable gl debug output to display warnings when we're using features not available to a specific opengl version.
https://stackoverflow.com/questions/34151202/emulate-minimum-opengl-specs
https://www.khronos.org/opengl/wiki/Debug_Output

**Comment by edwin0cheng** [comment]
I just changed the glutin side code to make it force to use OpenGL 3.1 or ES 2.0.

Would you mind to try master branch in your machine again ?(https://github.com/edwin0cheng/unigame/commit/82437bf670df34fb256947561db970517544cfae)

**Comment by jice-nospam** [comment]
same error on native with current master branch (web still works fine). 
I'll try to add the VAO to see if it works with ES 2.0

**Comment by edwin0cheng** [comment]
What is the gl version its shown ?? Still opengl 3.3 (Core profile) Mesa 17.2.8 or changed to 3.1 ?

**Comment by jice-nospam** [comment]
still 3.3. This is the driver version. I think nothing in the code can change it

**Comment by edwin0cheng** [comment]
Its strange, my machine can change it .....
In my machine:
*Before*
```
opengl 4.6.0 NVIDIA 388.13
shading language 4.60 NVIDIA
vendor NVIDIA Corporation
```
*After*
```
opengl 3.1.0 NVIDIA 388.13
shading language 1.40 NVIDIA via Cg compiler
vendor NVIDIA Corporation
```

**Comment by jice-nospam** [comment]
adding VAO fixes the native version, but my web version fails :
```
opengl WebGL 1.0
shading language WebGL GLSL ES 1.0
vendor Mozilla
[...]
TypeError: ctx.createVertexArray is not a function
```
To make it work, I have to change webgl.rs :
`common: GLContext::new(&canvas.clone().into(), "webgl2"),`

instead of `webgl`

I'm submitting a PR so you can check if it still works on your system

**Comment by edwin0cheng** [comment]
But i do not wanna to use webgl2 context, because ios still cannot use it T_T

**Comment by jice-nospam** [comment]
ok trying to PR a version that works on both webgl1 and webgl2

**Comment by edwin0cheng** [comment]
I still don't understand why cannot choose the OpenGL version in your machine. It it is not possible, an old OpenGL (based on 3.1) game could not run in your machine too ? Im so confused.

**Comment by jice-nospam** [comment]
yeah that's weird. Even stranger : my web version always shows `opengl WebGL 1.0` but `getContext('webgl2')` works fine... Virtual Box might be doing some weird tricks.
Anyway I've got a version that works, both native, webgl1 and webgl2. I'll PR so you can see if it's ok for you.

**Comment by edwin0cheng** [comment]
May i know what is your host machine os and guest machine os of your VM?

**Comment by jice-nospam** [comment]
host : windows 10 professional 64bits
guest : Ubuntu 17.10

**Comment by edwin0cheng** [comment]
Just a reminder, finally i understand why your machine would not working when i try to debug in mac. It is related to [this](https://stackoverflow.com/questions/20264814/glsl-version-130-on-mac-os-x-causes-error).
Basically, the spec said it is possible for vender to not support compatibility profiles.

**Comment by jice-nospam** [comment]
Indeed, the opengl String contains "Core profile". On another hand, this is
a virtual machine. Not sure if this happens often with host systems.

2018-03-04 22:00 GMT+01:00 Edwin Cheng <notifications@github.com>:

**Comment by edwin0cheng** [comment]
So right now i explicitly set it to use [Core Profile ](https://github.com/edwin0cheng/unrust/blob/master/uni-app/src/native_app.rs#L81). Didn't know whether it is default or not.
